// The error control codes of the DMR air interface, ETSI TS 102 361-1
// V2.7.1 (2026-05) Annex B.
//
// WHY THESE ARE NOT IN core/decode/dv_codes.h
//
// dv_codes.h holds the codes of three standards, one section per standard.
// DMR's Annex B is eleven codes, two product codes built from them and three
// interleavers, which is more than the other three put together, and every
// one of them is used by this mode and no other. Keeping the annex in one
// file means a reader checking it against the document reads one file in the
// order the annex is written.
//
// GENERATORS, CHECKED AGAINST THE PRINTED MATRICES
//
// Annex B.3 prints a generator polynomial and a generator matrix for each of
// its block codes. The polynomial is what this file carries and the matrix is
// what tests/decode/test_dmr.cpp checks it against, the rule dv_codes.h
// states and for the reason it gives. All seven regenerate their printed
// matrices row for row with the information bits most significant first and
// the parity in the order the table prints it, which was checked before any
// of this was written rather than assumed.
//
// DECODING IS NEAREST CODE WORD
//
// Every block code here has at most 4096 code words, so each is decoded by
// comparing against all of them, which is maximum likelihood by
// construction. core/decode/dv_codes.h makes the same choice for P25's NID
// and gives the reasoning; here the largest search is the Hamming (17,12)
// row code of the CACH, once per 120 ms.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>

#include "core/error.h"

namespace revenant::decode {

// ---------------------------------------------------------------------------
// The block codes, Annex B.3
// ---------------------------------------------------------------------------

// A systematic binary block code generated by a polynomial, shortened and
// optionally extended by an overall parity bit, the way Annex B.3 derives
// every one of its codes. A code word is held in the low n bits of a word,
// the first transmitted bit most significant, information then parity.
struct DmrBlockCode {
    unsigned n = 0;
    unsigned k = 0;

    // The generator polynomial, bit i the coefficient of x^i.
    std::uint32_t generator = 0;

    // Whether an overall even parity bit follows the cyclic code's parity,
    // which is how B.3.1 extends Golay (23,12) to (24,12) and B.3.2 extends
    // the (17,9) quadratic residue code.
    bool extended = false;

    // The minimum distance, so a caller can tell a correction the code
    // guarantees from the nearest code word to something further out.
    unsigned distance = 0;
};

// B.3.1, formula B.4: g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1, which
// the clause gives in octal as 6165. Golay (23,12,7), extended to (24,12,8)
// and shortened to (20,8). Table B.11 is the printed matrix.
inline constexpr DmrBlockCode kDmrGolay20{20, 8, 06165U, true, 8};

// B.3.2, formula B.5: G(x) = x^8 + x^5 + x^4 + x^3 + 1, octal 471, the
// primitive (17,9,5) quadratic residue code with its first two information
// bits deleted and a parity bit added. Table B.12.
inline constexpr DmrBlockCode kDmrQr16{16, 7, 0471U, true, 6};

// B.3.3, formula B.6: g(x) = x^5 + x^2 + 1, octal 45, shortened to (17,12).
// Table B.13.
inline constexpr DmrBlockCode kDmrHamming17{17, 12, 045U, false, 3};

// B.3.4, formula B.7: G(x) = x^4 + x + 1, octal 23, the primitive (15,11,3)
// code, which B.3.4 shortens to (13,9,3) and extends to (16,11,4). Tables
// B.14, B.15 and B.16.
inline constexpr DmrBlockCode kDmrHamming13{13, 9, 023U, false, 3};
inline constexpr DmrBlockCode kDmrHamming15{15, 11, 023U, false, 3};
inline constexpr DmrBlockCode kDmrHamming16{16, 11, 023U, true, 4};

// B.3.5, formula B.8: G(x) = x^3 + x + 1, octal 13. Table B.17.
inline constexpr DmrBlockCode kDmrHamming7{7, 4, 013U, false, 3};

// Encodes the low k bits of `information` into an n-bit code word.
[[nodiscard]] std::uint32_t dmr_block_encode(const DmrBlockCode& code, std::uint32_t information);

struct DmrBlockDecode {
    std::uint32_t information = 0;

    // The nearest code word, and how many bits the received word differs
    // from it in.
    std::uint32_t codeword = 0;
    std::uint32_t distance = 0;

    // True when the distance is more than the code corrects, (d-1)/2, so the
    // word is a detected error rather than a correction.
    bool detected = false;
};

// Nearest of the 2^k code words to the low n bits of `word`.
[[nodiscard]] DmrBlockDecode dmr_block_decode(const DmrBlockCode& code, std::uint32_t word);

// ---------------------------------------------------------------------------
// Reed-Solomon (12,9), B.3.6
// ---------------------------------------------------------------------------

// Formula B.14: GF(2^8) generated by alpha^8 + alpha^4 + alpha^3 + alpha^2 + 1.
// Tables B.19 and B.20 print the exponential and logarithm tables of the
// field, which the test regenerates from this.
inline constexpr std::uint32_t kDmrGf256Polynomial = 0x11DU;

[[nodiscard]] std::uint8_t dmr_gf256_exp(unsigned e);
// Zero has no logarithm and returns -1.
[[nodiscard]] int dmr_gf256_log(std::uint8_t value);
[[nodiscard]] std::uint8_t dmr_gf256_mul(std::uint8_t a, std::uint8_t b);

// Formula B.9: G(x) = (x + alpha)(x + alpha^2)(x + alpha^3), which formula
// B.10 prints as x^3 + 0e x^2 + 38 x + 40. Index is the degree.
[[nodiscard]] std::array<std::uint8_t, 4> dmr_rs_generator();

// Formulas B.11 to B.13: nine message octets, the first the highest degree,
// to three parity octets p2, p1, p0 in transmission order.
[[nodiscard]] std::array<std::uint8_t, 3> dmr_rs_parity(std::span<const std::uint8_t, 9> message);

struct DmrRsDecode {
    // False when the received word is more than one octet from a code word,
    // which is all a distance 4 code corrects.
    bool decoded = false;
    std::array<std::uint8_t, 12> codeword{};
    std::uint32_t corrected = 0;
};

// Syndromes at alpha^1 to alpha^3, a single error located by S2/S1 and
// confirmed by S3/S2, which is the whole of what a three-parity code can do.
// A word whose syndromes fit no single error comes back undecoded.
[[nodiscard]] DmrRsDecode dmr_rs_decode(std::span<const std::uint8_t, 12> received);

// ---------------------------------------------------------------------------
// CRCs and the checksum, B.3.7, B.3.8, B.3.11 and B.3.12
// ---------------------------------------------------------------------------

// B.3.7, formula B.16: G8(x) = x^8 + x^2 + x + 1, initial remainder zero and
// no inversion, over `bits` one per byte, first the highest degree.
[[nodiscard]] std::uint8_t dmr_crc8(std::span<const std::uint8_t> bits);

// B.3.8, formulas B.18 to B.20: GH(x) = x^16 + x^12 + x^5 + 1, initial
// remainder zero, and the result added to IH(x), every coefficient one, which
// is an inversion. Over whole octets, the first octet's MSB the highest
// degree.
[[nodiscard]] std::uint16_t dmr_crc_ccitt(std::span<const std::uint8_t> octets);

// B.3.11, formula B.26: the nine octets of a Full LC summed and reduced mod 31.
[[nodiscard]] std::uint8_t dmr_checksum5(std::span<const std::uint8_t, 9> lc);

// Table B.21, the Data Type CRC masks this decoder applies. Exclusive-ored
// into the CRC after it is computed and before the FEC on transmission, and
// after the FEC and before the check on reception.
inline constexpr std::uint16_t kDmrMaskPiHeader = 0x6969U;
inline constexpr std::uint32_t kDmrMaskVoiceLcHeader = 0x969696U;
inline constexpr std::uint32_t kDmrMaskTerminatorWithLc = 0x999999U;
inline constexpr std::uint16_t kDmrMaskCsbk = 0xA5A5U;
inline constexpr std::uint16_t kDmrMaskMbcHeader = 0xAAAAU;
inline constexpr std::uint16_t kDmrMaskDataHeader = 0xCCCCU;
inline constexpr std::uint16_t kDmrMaskUnifiedSingleBlock = 0x3333U;

// ---------------------------------------------------------------------------
// BPTC (196,96), B.1.1
// ---------------------------------------------------------------------------

// Bits one per byte throughout. For the 96 information bits index 0 is I(95);
// for the 196 transmitted bits index 0 is TX(195), which Annex E makes the
// first bit on the air.
inline constexpr std::size_t kDmrBptcInformationBits = 96;
inline constexpr std::size_t kDmrBptcBits = 196;

// Figure B.1 and formula B.1: the 96 bits into a 13 by 15 matrix behind three
// reserved zeros, each of the nine data rows a Hamming (15,11,3) word and each
// of the fifteen columns a Hamming (13,9,3) word, then every bit moved to
// index * 181 mod 196, with a fourth reserved zero at index 0.
[[nodiscard]] std::array<std::uint8_t, kDmrBptcBits> dmr_bptc196_encode(
    std::span<const std::uint8_t, kDmrBptcInformationBits> information);

struct DmrBptcDecode {
    std::array<std::uint8_t, kDmrBptcInformationBits> information{};

    // Bits the row and column codes changed between them.
    std::uint32_t corrected = 0;

    // True when every row and column is a code word after the passes, so
    // what came out is on the product code. False is a detected failure; the
    // information is still handed out, and the CRC or Reed-Solomon code
    // behind it is what decides.
    bool clean = false;
};

// De-interleaves and decodes by alternating row and column passes, each a
// nearest code word decision that corrects one error, until a pass changes
// nothing or four passes have run.
[[nodiscard]] DmrBptcDecode dmr_bptc196_decode(std::span<const std::uint8_t, kDmrBptcBits> received);

// ---------------------------------------------------------------------------
// Embedded signalling, B.2.1
// ---------------------------------------------------------------------------

inline constexpr std::size_t kDmrEmbeddedFragmentBits = 32;
inline constexpr std::size_t kDmrEmbeddedFragments = 4;
inline constexpr std::size_t kDmrEmbeddedBits = kDmrEmbeddedFragmentBits * kDmrEmbeddedFragments;

// Figure B.3: the 72 LC bits and the 5-bit checksum in seven Hamming
// (16,11,4) rows under a row of even column parity, read out down the columns
// into four 32-bit fragments. Index 0 of the result is TX(31) of the first
// fragment.
[[nodiscard]] std::array<std::uint8_t, kDmrEmbeddedBits> dmr_embedded_encode(
    std::span<const std::uint8_t, 9> lc);

struct DmrEmbeddedDecode {
    std::array<std::uint8_t, 9> lc{};
    std::uint32_t corrected = 0;

    // Every row decoded within the one error Hamming (16,11,4) corrects and
    // every column's parity checked.
    bool clean = false;

    // The B.3.11 checksum over the recovered octets matched the one carried.
    bool checksum_valid = false;
};

[[nodiscard]] DmrEmbeddedDecode dmr_embedded_decode(std::span<const std::uint8_t, kDmrEmbeddedBits> received);

// ---------------------------------------------------------------------------
// The CACH, B.2.3 and B.4.1
// ---------------------------------------------------------------------------

inline constexpr std::size_t kDmrCachBits = 24;
inline constexpr std::size_t kDmrCachPayloadBits = 17;
inline constexpr std::size_t kDmrShortLcFragments = 4;
inline constexpr std::size_t kDmrShortLcBits = kDmrCachPayloadBits * kDmrShortLcFragments;

// Figure B.6: the 28 Short LC bits and their B.3.7 CRC in three Hamming
// (17,12,3) rows under a row of even column parity, read out down the columns
// into four 17-bit CACH payloads. `lc` is the 28 bits one per byte, SLCO
// first.
[[nodiscard]] std::array<std::uint8_t, kDmrShortLcBits> dmr_short_lc_encode(
    std::span<const std::uint8_t, 28> lc);

struct DmrShortLcDecode {
    std::array<std::uint8_t, 28> lc{};
    std::uint32_t corrected = 0;
    bool clean = false;
    bool crc_valid = false;
};

[[nodiscard]] DmrShortLcDecode dmr_short_lc_decode(std::span<const std::uint8_t, kDmrShortLcBits> received);

// Figure B.9: where each bit of a CACH burst goes. The seven TACT bits, AT,
// TC, LCSS(1), LCSS(0) and the three Hamming (7,4) parity bits, sit at these
// positions of the 24, counted from TX(23), which is transmitted first; the
// seventeen payload bits fill the rest in order.
inline constexpr std::array<std::size_t, 7> kDmrCachTactPositions = {0, 4, 8, 12, 14, 18, 22};

struct DmrCachBits {
    // The seven TACT bits as one Hamming (7,4) word, AT the most significant.
    std::uint32_t tact = 0;
    std::array<std::uint8_t, kDmrCachPayloadBits> payload{};
};

[[nodiscard]] std::array<std::uint8_t, kDmrCachBits> dmr_cach_interleave(const DmrCachBits& bits);
[[nodiscard]] DmrCachBits dmr_cach_deinterleave(std::span<const std::uint8_t, kDmrCachBits> received);

}  // namespace revenant::decode
