// The error control codes the digital voice modes specify.
//
// Each one cites the clause that defines it. Where a standard prints both a
// generator and a worked table, the generator is what this file carries and
// the table is what the test checks it against: a generator is the rule and a
// table is an instance of it, and a file holding only the table cannot be
// audited against the document without retyping the document.
//
// Nothing here is shared between modes by accident. P25's NID BCH code and
// TETRA's block code are both cyclic codes over GF(2) and they are separate
// functions, because they are separate clauses of separate standards and a
// reader checking one should not have to establish that the other's
// requirements were also met by whatever was factored out.
//
// The exception is the convolutional machinery. TETRA's 16-state RCPC mother
// code and D-STAR's 4-state code are the same algorithm at two constraint
// lengths, so the Viterbi decoder is written once and parameterised, with the
// generators supplied by the mode.

#pragma once

#include <cstddef>
#include <cstdint>
#include <span>
#include <vector>

#include "core/error.h"

namespace revenant::decode {

// A bit, stored one per byte. Every code in this file works in this form
// rather than in packed words: the standards number bits individually and in
// several places in an order that is not the natural order of a machine word,
// so a packed representation would put a shift and a mask between the code and
// the clause that specifies it.
using BitSpan = std::span<std::uint8_t>;
using ConstBitSpan = std::span<const std::uint8_t>;

// A soft bit: positive means the receiver leaned towards zero, negative
// towards one, and the magnitude is the confidence. Sign convention chosen so
// the hard decision is (value < 0), which matches the way every slicer in this
// tree is written.
using SoftSpan = std::span<const float>;

// ---------------------------------------------------------------------------
// P25 Phase 1: the Network Identifier BCH code
// ---------------------------------------------------------------------------

// TIA-102.BAAA-A clause 8.5.2. The (63,16,23) primitive BCH code, generated by
// a 47th degree polynomial with 27 non-zero terms:
//
//     g(x) = 6331 1413 6723 5453 in octal
//
// The clause also prints the 16 by 64 systematic generator matrix. That matrix
// is not reproduced here, because it does not have to be: the polynomial above
// regenerates all 16 rows' 47 parity bits exactly, which
// tests/decode/test_p25p1.cpp checks against the printed octal.
inline constexpr std::uint64_t kP25NidGenerator = 06331141367235453ULL;

// TIA-102.BAAA-A clause 8.5: "A single parity bit is appended to the end to
// round out the NID code word to 64 bits."
//
// The clause does not say what that bit is a parity of, and it is not the
// parity of the whole word. What it is can be read off the two tables the
// clause does print. The generator matrix's 64th column is 1 for exactly two
// rows, the two least significant message bits, which are DUID(1) and DUID(0);
// so for a linear code the bit is DUID(1) XOR DUID(0). That rule reproduces
// every P value in Table 8-4, all six of them, which is the second independent
// check.
//
// Recorded at this length because a reader who assumes even parity, as this
// implementation first did, gets a code word that differs from the standard's
// in one bit and a decoder that still locks, still reports the right NAC, and
// is wrong.
[[nodiscard]] std::uint8_t p25_nid_trailing_parity(std::uint16_t nid_information);

// Encodes a 12-bit NAC and a 4-bit DUID into the 64 bits of the NID code word,
// most significant bit of the NAC first, per Table 8-3.
[[nodiscard]] Status p25_nid_encode(std::uint16_t nac, std::uint8_t duid, BitSpan out);

struct P25NidDecode {
    std::uint16_t nac = 0;
    std::uint8_t duid = 0;

    // Hamming distance from the received word to the code word chosen. The
    // code's minimum distance is 23, so any distance up to 11 is a correction
    // the code guarantees and anything above it is a guess. The caller decides
    // where to stop, beside the reason it chose that number.
    std::uint32_t corrected_bits = 0;
};

// Maximum likelihood decode of a 64-bit NID code word: the nearest of the
// 65536 code words, by Hamming distance.
//
// Exhaustive search rather than a syndrome decoder, and the reason is not
// laziness. A BCH decoder for d=23 needs Berlekamp-Massey over GF(2^6), a
// Chien search and error evaluation, which is several hundred lines that can
// be subtly wrong in a way that only shows at high error counts. There are
// 65536 code words and one NID arrives every 180 ms at most, so the search
// costs about four megabit-comparisons per frame on a machine that has
// billions to spare, and it is maximum likelihood by construction rather than
// by argument.
[[nodiscard]] Expected<P25NidDecode> p25_nid_decode(ConstBitSpan word);

// ---------------------------------------------------------------------------
// P25 Phase 1: the shortened Golay code
// ---------------------------------------------------------------------------

// TIA-102.BAAA-A clause 5.7, Table 5-3. The (18,6,8) shortened Golay code, as
// the six rows of its systematic generator matrix in octal. Left six columns
// are the identity, right twelve are the parity check.
inline constexpr std::uint32_t kP25Golay18Rows[6] = {
    0403315U, 0201547U, 0106706U, 0045227U, 0024476U, 0014353U,
};

// Encodes 6 information bits into an 18-bit code word, most significant first.
[[nodiscard]] std::uint32_t p25_golay18_encode(std::uint8_t information);

struct Golay18Decode {
    std::uint8_t information = 0;
    std::uint32_t corrected_bits = 0;
};

// Nearest of the 64 code words. d = 8, so up to three errors are corrected and
// a fourth is detected as an ambiguous distance.
[[nodiscard]] Golay18Decode p25_golay18_decode(std::uint32_t word);

// ---------------------------------------------------------------------------
// Convolutional codes
// ---------------------------------------------------------------------------

// A feedforward convolutional code, described the way both standards describe
// theirs: a constraint length and a set of generator polynomials, each with
// the coefficient of D^0 in the least significant bit.
struct ConvolutionalCode {
    // Number of D terms the encoder remembers, so the register is this wide
    // and the code has 2^memory states. TETRA's is 4 and D-STAR's is 2.
    std::uint32_t memory = 0;

    // One output per generator, per input bit, in the order the standard
    // lists them.
    std::span<const std::uint32_t> generators;
};

// Encodes `input` into `input.size() * generators.size()` output bits, with
// the register starting at zero. The caller appends the flush bits to `input`
// itself, because both standards specify the flush as part of the bit sequence
// being encoded rather than as something the encoder adds.
[[nodiscard]] Expected<std::vector<std::uint8_t>> convolutional_encode(
    const ConvolutionalCode& code, ConstBitSpan input);

// Soft-decision Viterbi decode, returning the most likely input sequence.
//
// `soft` holds one value per encoded bit, in the sign convention above.
// `terminated` says whether the encoder was flushed to the zero state, which
// both of these standards do; when true the traceback starts from state zero
// rather than from the best final state, which is worth about a decibel at the
// tail of a short block.
[[nodiscard]] Expected<std::vector<std::uint8_t>> viterbi_decode(const ConvolutionalCode& code,
                                                                 SoftSpan soft, bool terminated);

// ---------------------------------------------------------------------------
// D-STAR
// ---------------------------------------------------------------------------

// JARL standard Ver 7.0 clause Ap2.1, from the encoder-structure figure in
// that clause: rate 1/2, constraint length 3, G1(D) = 1 + D + D^2 and
// G2(D) = 1 + D^2, with the G1 output taken as the odd output and G2 as the
// even one.
//
// THE CLAUSE BODY CONTRADICTS ITS OWN FIGURE AND THE FIGURE IS RIGHT.
//
// Ap2.1's text says, in the same three bullets, that the code is rate 1/2 with
// constraint length 3 and that "the generator polynomial value is 0x8408
// (0x1021 with its LSB and MSB reversed)". 0x8408 is sixteen bits and a rate
// 1/2 constraint length 3 code has two three-bit generators, so the text
// cannot be describing this code. 0x1021 is the CRC-CCITT polynomial, which is
// what clause 4.1.1 k specifies for P_FCS, so what happened is that the FCS
// generator was written into the FEC clause. The boxed figure in the same
// clause gives G1 and G2 explicitly and is what this implements.
//
// The figure and the numbered procedure disagree about the flush as well. The
// figure's box says four hangover bits; step 3 of the procedure says two zero
// bits are input after the header. Two is what a memory-2 register needs and
// two is what makes the encoded length come out at 660, which is the length
// the interleave matrix in Ap2.2 and the frame diagram in clause 4.1.2 both
// state. So the procedure is right and the figure's hangover count is not
// reachable from anything else in the document.
inline constexpr std::uint32_t kDStarConvGenerators[2] = {0b111U, 0b101U};
inline constexpr std::uint32_t kDStarConvMemory = 2;

// Clause 4.1.2, from the frame diagram: the radio header runs from flag 1 to
// P_FCS and is 41 bytes, and the diagram labels the error-corrected span 660
// bits. 41 bytes is 328 bits, plus the two flush bits of Ap2.1 step 3 is 330,
// and at rate 1/2 that is 660.
inline constexpr std::size_t kDStarHeaderBytes = 41;
inline constexpr std::size_t kDStarHeaderBits = kDStarHeaderBytes * 8;
inline constexpr std::size_t kDStarHeaderEncodedBits = (kDStarHeaderBits + 2) * 2;

// JARL Ver 7.0 clause Ap2.2, the interleave structure matrix. The 660 encoded
// bits are written into a 24 row by 28 column matrix down the columns, so the
// cell at row r and column c holds encoded bit c*24 + r, and are transmitted
// by reading the matrix across the rows. Cells whose index reaches 660 do not
// exist, which is why the last four rows are one column short.
//
// Returns, for each transmitted position, the index of the encoded bit that
// goes there. Interleaving is applying it and deinterleaving is inverting it.
[[nodiscard]] std::vector<std::uint16_t> dstar_interleave_map();

// JARL Ver 7.0 clause Ap1.1: S(x) = x^7 + x^4 + 1, initialised to all ones and
// re-initialised at each point where scrambling starts. Clause Ap1.3 says the
// voice packet scrambles the radio header and the data frames, and excludes
// the bit sync, the frame sync, the in-data resynchronisation signals and the
// last frame.
//
// Applied in place, and self-inverse, so one function serves both ends.
void dstar_scramble(BitSpan bits);

// Clause 4.1.1 k: G(x) = x^16 + x^12 + x^5 + 1, CRC-CCITT, over the header
// from flag 1 to the end of own callsign 2.
//
// `bytes` is the 39 header bytes the FCS covers. Returns the 16-bit P_FCS.
[[nodiscard]] std::uint16_t dstar_header_fcs(std::span<const std::uint8_t> bytes);

// ---------------------------------------------------------------------------
// TETRA
// ---------------------------------------------------------------------------

// ETSI EN 300 392-2 V3.8.1 clause 8.2.3.1.1, the 16-state mother code of rate
// 1/4:
//
//     G1(D) = 1 + D + D^4
//     G2(D) = 1 + D^2 + D^3 + D^4
//     G3(D) = 1 + D + D^2 + D^4
//     G4(D) = 1 + D + D^3 + D^4
inline constexpr std::uint32_t kTetraMotherGenerators[4] = {
    0b10011U, 0b11101U, 0b10111U, 0b11011U,
};
inline constexpr std::uint32_t kTetraMotherMemory = 4;

// Clause 8.2.3.1.2 and 8.2.3.1.3. The rate 2/3 code keeps three of every eight
// mother bits, at the positions t = 3 coefficients P(1) = 1, P(2) = 2,
// P(3) = 5 select:
//
//     b3(j) = V(k),  k = 8*((j-1) div 3) + P(1 + (j-1) mod 3)
//
// Returns, for each of `punctured_bits` output positions, the index into the
// mother code's output that it came from.
[[nodiscard]] std::vector<std::uint32_t> tetra_rate_two_thirds_map(std::size_t punctured_bits);

// Clause 8.2.4.1. A (K, a) block interleaver re-orders K bits by
// b4(k) = b3(i) with k = 1 + ((a * i) mod K), one-based throughout.
//
// Returns, for each interleaved position, the index it came from, zero-based.
[[nodiscard]] Expected<std::vector<std::uint32_t>> tetra_block_interleave_map(std::size_t k,
                                                                              std::size_t a);

// Clause 8.2.5. The scrambling sequence from the connection polynomial
//
//   c(x) = 1 + x + x^2 + x^4 + x^5 + x^7 + x^8 + x^10 + x^11 + x^12
//          + x^16 + x^22 + x^23 + x^26 + x^32
//
// with p(k) = sum over i of c_i * p(k-i), initialised p(k) = e(1-k) for
// k = -29..0 and p(k) = 1 for k = -31 and -30.
//
// `extended_colour_code` is e(1) through e(30), one bit per byte. Clause
// 8.2.5.2 requires all thirty bits to be zero for the BSCH, which is what
// makes the broadcast synchronisation channel readable by a receiver that does
// not yet know the cell's colour code.
[[nodiscard]] Expected<std::vector<std::uint8_t>> tetra_scrambling_sequence(
    ConstBitSpan extended_colour_code, std::size_t length);

// Clause 8.2.3.3, the (K1 + 16, K1) block code. Systematic: the K1 information
// bits followed by sixteen check bits from
//
//     G(X) = X^16 + X^12 + X^5 + X^0
//
// with the ones preset and the ones postset that clause 8.2.3.3's two sums of
// X^i supply, which is the ITU-T X.25 frame check sequence the clause cites.
//
// Returns the sixteen check bits, b2(K1+1) through b2(K1+16), in transmission
// order, which clause 8.2.3.3 gives as b2(k) = f(K1 + 16 - k).
[[nodiscard]] std::vector<std::uint8_t> tetra_block_code_parity(ConstBitSpan information);

// True when `word`, being K1 information bits followed by the sixteen check
// bits, checks out.
[[nodiscard]] bool tetra_block_code_verify(ConstBitSpan word);

}  // namespace revenant::decode
