// FX.25: AX.25 frames inside a Reed-Solomon codeblock, found by a 64-bit
// correlation tag.
//
// SPECIFICATION
//
// "FX.25: Forward Error Correction Extension to AX.25 Link Protocol For
// Amateur Packet Radio", Stensat Group LLC (J. McGuire, I. Galysh, K.
// Doherty, H. Heidt, D. Neimi), Version 0.01 DRAFT, document version
// 0.01.06, dated 01 September 2006, the paper presented at the TAPR/ARRL DCC
// 2006. Ten pages. Retrieved 2026-10-02. https://www.stensat.org/docs/
// FX-25_01_06.pdf did not answer (connection timed out), so the copy read is
// the Internet Archive's capture of that URL,
// https://web.archive.org/web/20220904094750/http://www.stensat.org/docs/
// FX-25_01_06.pdf, whose content digest is the same as the archive's first
// capture of it, made in October 2006.
//
// The document has no numbered clauses. Sections are cited by their headings:
// "Protocol Summary", "Physical Layer Considerations", "Correlation Tag
// Details", "AX.25 Packet Requirements", "Pad Requirements", "FEC
// Algorithms" with its Table 1, and "Multi-Frame Blocks".
//
// WHAT THE DOCUMENT DOES NOT SAY
//
// It names its codes RS(255,239), RS(255,223) and RS(255,191) and their
// shortened forms, and it does not give the Galois field's polynomial, the
// generator's first consecutive root, or which end of the codeblock is the
// high-order coefficient. It cites the CCSDS telemetry coding standard as one
// user of Reed-Solomon codes, not as the definition of FX.25's. The three
// parameters below are therefore engineering choices, each labelled where it
// is set, and a station whose code differs in any of them will have its
// FX.25 codeblocks refused here while its AX.25 frame inside still decodes
// the ordinary way. No on-air FX.25 recording has been checked against them.
//
// It also does not say how many bit errors a receiver should tolerate in the
// correlation tag, only that the tag is "designed to provide good correlation
// even in the presence of channel errors". The tolerance is an engineering
// choice, set and argued below.
//
// CLEAN ROOM
//
// No FX.25 or Reed-Solomon implementation was read.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <vector>

#include "core/decode/reed_solomon.h"
#include "core/dsp/types.h"
#include "core/error.h"

namespace revenant::decode {

using dsp::SampleIndex;

// "Correlation Tag Details": eight bytes, a leading zero and a 63-bit Gold
// code, "represented in 64-bit notation, with the MSB at the left and the LSB
// at the right. Transmission order of the bytes for Tag_01 would be 0x3E
// 0x2F 0x53 0x8A 0xDF 0xB7 0x4D 0xB7", and "Physical Layer Considerations":
// "All bytes/octets in the FX.25 frame are transmitted LSb first". So bit 0
// of the 64-bit value goes to air first and bit 63 last.
inline constexpr std::size_t kFx25TagBits = 64;

// One row of Table 1 that assigns a code.
struct Fx25Mode {
    // The tag's index, Tag_01 to Tag_0B.
    std::uint8_t index = 0;
    std::uint64_t tag = 0;
    // Codeblock octets, information octets, and the check octets between
    // them, n - k.
    std::size_t n = 0;
    std::size_t k = 0;
    [[nodiscard]] constexpr std::size_t check() const { return n - k; }
};

// Table 1, "FEC Algorithms and Correlation Tag Value Assignments". Tag_00 and
// Tag_40 are reserved and Tag_0C onward undefined, so none of them selects a
// code and none is listed.
inline constexpr std::array<Fx25Mode, 11> kFx25Modes = {{
    {0x01, 0xB74DB7DF8A532F3EULL, 255, 239},
    {0x02, 0x26FF60A600CC8FDEULL, 144, 128},
    {0x03, 0xC7DC0508F3D9B09EULL, 80, 64},
    {0x04, 0x8F056EB4369660EEULL, 48, 32},
    {0x05, 0x6E260B1AC5835FAEULL, 255, 223},
    {0x06, 0xFF94DC634F1CFF4EULL, 160, 128},
    {0x07, 0x1EB7B9CDBC09C00EULL, 96, 64},
    {0x08, 0xDBF869BD2DBB1776ULL, 64, 32},
    {0x09, 0x3ADB0C13DEAE2836ULL, 255, 191},
    {0x0A, 0xAB69DB6A543188D6ULL, 192, 128},
    {0x0B, 0x4A4ABEC4A724B796ULL, 128, 64},
}};

// "FEC Algorithms": every code in Table 1 is RS(255,239), RS(255,223) or
// RS(255,191) or one of them shortened, so three numbers of check symbols.
inline constexpr std::array<std::size_t, 3> kFx25CheckSymbolCounts = {16, 32, 64};

// ENGINEERING CHOICE, the document being silent as the header says: the
// field is GF(2^8) generated by x^8 + x^4 + x^3 + x^2 + 1, the primitive
// polynomial most often used for octet Reed-Solomon codes, and the
// generator's roots are alpha^1 to alpha^(n-k), alpha being x.
inline constexpr unsigned kFx25FieldPolynomial = 0x11D;
inline constexpr unsigned kFx25FirstRoot = 1;

// ENGINEERING CHOICE: a received 64-bit window is taken as a tag when it
// differs from one in no more than 8 bits. The eleven assigned tags, with the
// reserved and undefined ones of Table 1 included, are at least 24 bits from
// one another, so a window within 8 of one tag is at least 16 from every
// other and two tags are never confused. A window made of preamble flags and
// the first part of a tag, the only thing a receiver sees just before a real
// tag, is at least 17 bits from every assigned tag, so the tolerance cannot
// fire a bit early either; tests/decode/test_fx25.cpp checks both figures
// from Table 1. Eight errors in 64 bits is a bit error rate of 12 percent, far
// past the point where the codeblock behind it is correctable.
inline constexpr unsigned kFx25TagTolerance = 8;

// The mode whose tag is within kFx25TagTolerance bits of `window`, the 64
// most recent bits with the earliest in bit 0, and how many bits differ.
struct Fx25TagMatch {
    const Fx25Mode* mode = nullptr;
    unsigned errors = 0;
};
[[nodiscard]] std::optional<Fx25TagMatch> fx25_match_tag(std::uint64_t window);

[[nodiscard]] const Fx25Mode* fx25_mode(std::uint8_t index);

// The Reed-Solomon parameters FX.25 uses for `check_symbols`, with the
// engineering choices above.
[[nodiscard]] Rs8Params fx25_rs_params(std::size_t check_symbols);

// One codeblock received after a tag.
struct Fx25Block {
    const Fx25Mode* mode = nullptr;
    unsigned tag_errors = 0;
    // Symbols the Reed-Solomon decoder changed, or nothing when it refused
    // the codeblock.
    std::optional<std::size_t> corrected;
    // The k information octets, corrected when the decoder accepted them.
    std::vector<std::uint8_t> information;
    // The audio sample each information bit came from, 8k of them, least
    // significant bit of the first octet first.
    std::vector<SampleIndex> samples;
};

// The bit-level FX.25 receiver: a 64-bit window searched for a tag after
// every bit, and once one is found, "Protocol Summary"'s FEC Codeblock
// collected, n octets least significant bit first, and decoded. It sees the
// same bits the HDLC deframer does, after NRZI, because "Physical Layer
// Considerations" puts NRZI below the whole FX.25 frame.
class Fx25Receiver {
public:
    [[nodiscard]] static Expected<Fx25Receiver> create();

    void push(std::uint8_t bit, SampleIndex sample, std::vector<Fx25Block>& out);

    // True between a tag and the end of its codeblock. AX.25 frames the
    // ordinary deframer finishes in that time sit inside the codeblock.
    [[nodiscard]] bool collecting() const { return mode_ != nullptr; }

    void reset();

private:
    Fx25Receiver() = default;

    [[nodiscard]] const Rs8Codec& codec_for(std::size_t check_symbols) const;

    std::vector<Rs8Codec> codecs_;
    std::uint64_t window_ = 0;
    // Bits in the window since the last reset or the end of the last
    // codeblock, so a tag is never matched against a window that is partly
    // the previous codeblock.
    std::size_t window_fill_ = 0;
    const Fx25Mode* mode_ = nullptr;
    unsigned tag_errors_ = 0;
    std::vector<std::uint8_t> bits_;
    std::vector<SampleIndex> samples_;
};

}  // namespace revenant::decode
